name: 'Storage Branch Commit'
description: 'Commit files to a storage branch'
author: 'taqm'

inputs:
  branch:
    description: 'Name of the storage branch to commit to'
    required: true
    default: 'storage'
  from:
    description: 'Source file path'
    required: true
  to:
    description: 'Destination file path in storage branch'
    required: true
  working-directory:
    description: 'Working directory for source path'
    required: false
    default: '.'
  message:
    description: 'Commit message'
    required: false
    default: 'Update storage files'

runs:
  using: 'composite'
  steps:
    - name: Commit files to storage branch
      shell: bash
      env:
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_FROM: ${{ inputs.from }}
        INPUT_TO: ${{ inputs.to }}
        INPUT_WORKING_DIR: ${{ inputs.working-directory }}
        INPUT_MESSAGE: ${{ inputs.message }}
      run: bash "${{ github.action_path }}/commit.sh"
