name: 'Storage Branch Checkout'
description: 'Checkout files from a storage branch'
author: 'taqm'

inputs:
  branch:
    description: 'Name of the storage branch to checkout from'
    required: true
    default: 'storage'
  from:
    description: 'Source file path in storage branch'
    required: true
  to:
    description: 'Destination file path'
    required: true
  working-directory:
    description: 'Working directory for destination path'
    required: false
    default: '.'
  fail-on-missing:
    description: 'Fail if source file does not exist in the storage branch'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout storage branch files
      shell: bash
      env:
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_FROM: ${{ inputs.from }}
        INPUT_TO: ${{ inputs.to }}
        INPUT_WORKING_DIR: ${{ inputs.working-directory }}
        INPUT_FAIL_ON_MISSING: ${{ inputs.fail-on-missing }}
      run: bash "${{ github.action_path }}/checkout.sh"
